# Generated by Django 5.2.5 on 2025-11-13 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='Contacto',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
