# Generated by Django 5.2.5 on 2025-11-13 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_perfilusuario_contacto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilusuario',
            name='fotoPerfil',
            field=models.ImageField(blank=True, default='usuarios_fotos/default_1.png', upload_to='usuarios_fotos/'),
            preserve_default=False,
        ),
    ]
