# Generated by Django 5.2.5 on 2025-10-28 01:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Publicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipoMuro', models.CharField(choices=[('AYUDAS', 'Ayudas'), ('PRESTAMOS', 'Prestamos'), ('SERVICIOS', 'Servicios')], max_length=10)),
                ('contenido', models.TextField(verbose_name='Comentario')),
                ('fechaCreacion', models.DateTimeField(auto_now_add=True)),
                ('modalidad', models.CharField(blank=True, choices=[('PRESENCIAL', 'Presencial'), ('ONLINE', 'Online'), ('AMBAS', 'Ambas')], max_length=10, null=True)),
                ('tipoSesion', models.CharField(blank=True, choices=[('INDIVIDUAL', 'Individual'), ('GRUPAL', 'Grupal'), ('CUALQUIERA', 'Cualquiera de las dos')], max_length=15, null=True)),
                ('asignatura', models.CharField(blank=True, choices=[('ARQUITECTURA', 'Arquitectura'), ('FISICA', 'Fisica'), ('OBRAS CIVILES', 'Obras Civiles'), ('BIOTECNOLOGIA', 'Biotecnologia'), ('COMERCIAL', 'Comercial'), ('ELECTRICA', 'Electrica'), ('ELECTRONICA', 'Electronica'), ('HUMANISTICO', 'Humanistico'), ('MECANICA', 'Mecanica'), ('INDUSTRIAS', 'Industrias'), ('DISEÑO', 'Diseño'), ('INFORMATICA', 'Informatica'), ('DISEÑO', 'Diseño'), ('QUIMICA', 'Quimica y Ambiental'), ('MATEMATICAS', 'Matematicas'), ('DISEÑO', 'Diseño'), ('MINAS', 'Minas, Metalurgia, Materiales'), ('QUIMICA', 'Quimica')], max_length=20, null=True)),
                ('materialPrestamo', models.CharField(blank=True, max_length=150, null=True)),
                ('cantMaterial', models.PositiveIntegerField(blank=True, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
