# Generated by Django 5.2.5 on 2025-10-29 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicaciones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicacion',
            name='titulo',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
