# Generated by Django 5.2.5 on 2025-11-03 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicaciones', '0003_comentario'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicacion',
            name='fotoMaterial',
            field=models.ImageField(blank=True, null=True, upload_to='publicaciones_fotos/'),
        ),
    ]
