# Generated by Django 5.2.5 on 2025-11-11 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicaciones', '0004_publicacion_fotomaterial'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicacion',
            name='Comunicacion',
            field=models.CharField(blank=True, choices=[('CORREO', 'Correo Institucional'), ('Redes Sociales (Instagram, Facebook, WhatsApp, etc.)', 'OTROS')], max_length=59, null=True),
        ),
    ]
