# Generated by Django 5.2.5 on 2025-11-11 14:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicaciones', '0005_publicacion_comunicacion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publicacion',
            name='Comunicacion',
        ),
        migrations.AddField(
            model_name='publicacion',
            name='diaPref',
            field=models.CharField(blank=True, choices=[('LUNES', 'Lunes'), ('MARTES', 'Martes'), ('MIERCOLES', 'Miercoles'), ('JUEVES', 'Jueves'), ('VIERNES', 'Viernes')], max_length=15, null=True),
        ),
        migrations.CreateModel(
            name='FiltrarPreferencias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modalidad', models.CharField(blank=True, choices=[('PRESENCIAL', 'Presencial'), ('ONLINE', 'Online'), ('AMBAS', 'Ambas')], max_length=10, null=True)),
                ('Comunicacion', models.CharField(blank=True, choices=[('CORREO', 'Correo Institucional'), ('OTROS', 'Redes Sociales (Instagram, Facebook, WhatsApp, etc.)')], max_length=59, null=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
