# Generated by Django 5.2.5 on 2025-11-11 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicaciones', '0006_remove_publicacion_comunicacion_publicacion_diapref_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='filtrarpreferencias',
            name='asignatura',
            field=models.CharField(blank=True, choices=[('ARQUITECTURA', 'Arquitectura'), ('FISICA', 'Fisica'), ('OBRAS CIVILES', 'Obras Civiles'), ('BIOTECNOLOGIA', 'Biotecnologia'), ('COMERCIAL', 'Comercial'), ('ELECTRICA', 'Electrica'), ('ELECTRONICA', 'Electronica'), ('HUMANISTICO', 'Humanistico'), ('MECANICA', 'Mecanica'), ('INDUSTRIAS', 'Industrias'), ('DISEÑO', 'Diseño'), ('INFORMATICA', 'Informatica'), ('DISEÑO', 'Diseño'), ('QUIMICA', 'Quimica y Ambiental'), ('MATEMATICAS', 'Matematicas'), ('DISEÑO', 'Diseño'), ('MINAS', 'Minas, Metalurgia, Materiales'), ('QUIMICA', 'Quimica')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='filtrarpreferencias',
            name='dias',
            field=models.CharField(blank=True, choices=[('LUNES', 'Lunes'), ('MARTES', 'Martes'), ('MIERCOLES', 'Miercoles'), ('JUEVES', 'Jueves'), ('VIERNES', 'Viernes')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='filtrarpreferencias',
            name='metododeestudio',
            field=models.CharField(blank=True, choices=[('MAPAS MENTALES', 'Mapas Mentales'), ('RESUMENES', 'Resúmenes'), ('TECNICA POMODORO', 'Técnica Pomodoro'), ('TECNICAS DE MEMORIZACION', 'Técnicas de Memorización'), ('APUNTES', 'Apuntes')], max_length=30, null=True),
        ),
    ]
