# Generated by Django 5.2.5 on 2025-11-11 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicaciones', '0007_filtrarpreferencias_asignatura_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='publicacion',
            old_name='diaPref',
            new_name='dias',
        ),
        migrations.AddField(
            model_name='publicacion',
            name='Comunicacion',
            field=models.CharField(blank=True, choices=[('CORREO', 'Correo Institucional'), ('OTROS', 'Redes Sociales (Instagram, Facebook, WhatsApp, etc.)')], max_length=59, null=True),
        ),
        migrations.AddField(
            model_name='publicacion',
            name='metododeestudio',
            field=models.CharField(blank=True, choices=[('MAPAS MENTALES', 'Mapas Mentales'), ('RESUMENES', 'Resúmenes'), ('TECNICA POMODORO', 'Técnica Pomodoro'), ('TECNICAS DE MEMORIZACION', 'Técnicas de Memorización'), ('APUNTES', 'Apuntes')], max_length=30, null=True),
        ),
    ]
