# Generated by Django 5.2.5 on 2025-11-12 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicaciones', '0008_rename_diapref_publicacion_dias_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='filtrarpreferencias',
            name='tipoSesion',
            field=models.CharField(blank=True, choices=[('INDIVIDUAL', 'Individual'), ('GRUPAL', 'Grupal'), ('CUALQUIERA', 'Cualquiera de las dos')], max_length=15, null=True),
        ),
    ]
